# Generated by Django 5.0.6 on 2024-07-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_rooms_options_rooms_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
